#ifndef DDS_HEADER_H
#define DDS_HEADER_H
#include <cstdint>

#ifdef _WIN32
#pragma pack(push, 1)
#else
#pragma pack(1)
#endif

typedef uint32_t DWORD;
typedef uint32_t UINT;


enum DDS_Flags : DWORD
{
	DDSD_CAPS         = 0x1l,      // Required in every .dds file.
	DDSD_HEIGHT       = 0x2l,      // Required in every .dds file.
	DDSD_WIDTH        = 0x4l,      // Required in every .dds file.
	DDSD_PITCH        = 0x8l,      // Required when pitch is provided for an uncompressed texture.
	DDSD_PIXELFORMAT  = 0x1000l,   // Required in every .dds file.
	DDSD_MIPMAPCOUNT  = 0x20000l,  // Required in a mipmapped texture.
	DDSD_LINEARSIZE   = 0x80000l,  // Required when pitch is provided for a compressed texture.
	DDSD_DEPTH        = 0x800000l, // Required in a depth texture.

	DDS_FOURCC      = 0x00000004,
	DDS_RGB         = 0x00000040,
	DDS_RGBA        = 0x00000041,
	DDS_LUMINANCE   = 0x00020000,
	DDS_LUMINANCEA  = 0x00020001,
	DDS_ALPHAPIXELS = 0x00000001,
	DDS_ALPHA       = 0x00000002,
	DDS_PAL8        = 0x00000020,
	DDS_PAL8A       = 0x00000021,
	DDS_BUMPDUDV    = 0x00080000,
};


#ifndef MAKEFOURCC
    #define MAKEFOURCC(ch0, ch1, ch2, ch3) \
                (static_cast<uint32_t>(static_cast<uint8_t>(ch0)) \
                | (static_cast<uint32_t>(static_cast<uint8_t>(ch1)) << 8) \
                | (static_cast<uint32_t>(static_cast<uint8_t>(ch2)) << 16) \
                | (static_cast<uint32_t>(static_cast<uint8_t>(ch3)) << 24))
#endif /* defined(MAKEFOURCC) */

struct DDS_PIXELFORMAT {
  DWORD dwSize{sizeof(DDS_PIXELFORMAT)};
  DWORD dwFlags{};
  DWORD dwFourCC{};
  DWORD dwRGBBitCount{};
  DWORD dwRBitMask{};
  DWORD dwGBitMask{};
  DWORD dwBBitMask{};
  DWORD dwABitMask{};
};

struct DDS_HEADER {
  DWORD           dwSize{sizeof(DDS_HEADER)};
  DWORD           dwFlags{0x1007}; //used
  DWORD           dwHeight{}; //used
  DWORD           dwWidth{}; //used
  DWORD           dwPitchOrLinearSize{}; //used
  DWORD           dwDepth{0};
  DWORD           dwMipMapCount{0};
  DWORD           dwReserved1[11]{};
  DDS_PIXELFORMAT ddspf; //used
  DWORD           dwCaps{0x1000};
  DWORD           dwCaps2{};
  DWORD           dwCaps3{};
  DWORD           dwCaps4{};
  DWORD           dwReserved2{};
};

enum
{
	TYPE_DDS  = 0x20534444,
	TYPE_DX10 = 0x30315844,
	TYPE_BITS = 0x53544942,

	TYPE_DXT1 =  MAKEFOURCC('D','X','T','1'),
	TYPE_DXT2 =  MAKEFOURCC('D','X','T','2'),
	TYPE_DXT3 =  MAKEFOURCC('D','X','T','3'),
	TYPE_DXT4 =  MAKEFOURCC('D','X','T','4'),
	TYPE_DXT5 = MAKEFOURCC('D','X','T','5'),
	TYPE_BC4_UNORM = MAKEFOURCC('B','C','4','U'),
	TYPE_BC4_SNORM = MAKEFOURCC('B','C','4','S'),
	TYPE_BC5_UNORM = MAKEFOURCC('B','C','5','U'),
	TYPE_BC5_SNORM = MAKEFOURCC('B','C','5','S'),
	TYPE_RGBG = MAKEFOURCC('R','G','B','G'),
	TYPE_GRGB = MAKEFOURCC('G','R','G','B'),
	TYPE_UVVY = MAKEFOURCC('U','V','V','Y'),
	TYPE_YUY2 = MAKEFOURCC('Y','U','Y','2'),
	TYPE_ATI2 = MAKEFOURCC('A','T','I','2'),

	TYPE_RGBA16_UNORM = 36,
	TYPE_RGBA16_SNORM = 110,
	TYPE_R16_FLOAT    = 111,
	TYPE_RG16_FLOAT = 112,
	TYPE_RGBA16_FLOAT = 113,
	TYPE_R32_FLOAT    = 114,
	TYPE_RG32_FLOAT   = 115,
	TYPE_RGBA32_FLOAT = 116,
	TYPE_CxV8U8       = 117
};

enum D3D10_RESOURCE_DIMENSION {
  D3D10_RESOURCE_DIMENSION_UNKNOWN,
  D3D10_RESOURCE_DIMENSION_BUFFER,
  D3D10_RESOURCE_DIMENSION_TEXTURE1D,
  D3D10_RESOURCE_DIMENSION_TEXTURE2D,
  D3D10_RESOURCE_DIMENSION_TEXTURE3D
};

enum DXGI_FORMAT {
  DXGI_FORMAT_UNKNOWN,
  DXGI_FORMAT_R32G32B32A32_TYPELESS,
  DXGI_FORMAT_R32G32B32A32_FLOAT,
  DXGI_FORMAT_R32G32B32A32_UINT,
  DXGI_FORMAT_R32G32B32A32_SINT,
  DXGI_FORMAT_R32G32B32_TYPELESS,
  DXGI_FORMAT_R32G32B32_FLOAT,
  DXGI_FORMAT_R32G32B32_UINT,
  DXGI_FORMAT_R32G32B32_SINT,
  DXGI_FORMAT_R16G16B16A16_TYPELESS,
  DXGI_FORMAT_R16G16B16A16_FLOAT,
  DXGI_FORMAT_R16G16B16A16_UNORM,
  DXGI_FORMAT_R16G16B16A16_UINT,
  DXGI_FORMAT_R16G16B16A16_SNORM,
  DXGI_FORMAT_R16G16B16A16_SINT,
  DXGI_FORMAT_R32G32_TYPELESS,
  DXGI_FORMAT_R32G32_FLOAT,
  DXGI_FORMAT_R32G32_UINT,
  DXGI_FORMAT_R32G32_SINT,
  DXGI_FORMAT_R32G8X24_TYPELESS,
  DXGI_FORMAT_D32_FLOAT_S8X24_UINT,
  DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS,
  DXGI_FORMAT_X32_TYPELESS_G8X24_UINT,
  DXGI_FORMAT_R10G10B10A2_TYPELESS,
  DXGI_FORMAT_R10G10B10A2_UNORM,
  DXGI_FORMAT_R10G10B10A2_UINT,
  DXGI_FORMAT_R11G11B10_FLOAT,
  DXGI_FORMAT_R8G8B8A8_TYPELESS,
  DXGI_FORMAT_R8G8B8A8_UNORM,
  DXGI_FORMAT_R8G8B8A8_UNORM_SRGB,
  DXGI_FORMAT_R8G8B8A8_UINT,
  DXGI_FORMAT_R8G8B8A8_SNORM,
  DXGI_FORMAT_R8G8B8A8_SINT,
  DXGI_FORMAT_R16G16_TYPELESS,
  DXGI_FORMAT_R16G16_FLOAT,
  DXGI_FORMAT_R16G16_UNORM,
  DXGI_FORMAT_R16G16_UINT,
  DXGI_FORMAT_R16G16_SNORM,
  DXGI_FORMAT_R16G16_SINT,
  DXGI_FORMAT_R32_TYPELESS,
  DXGI_FORMAT_D32_FLOAT,
  DXGI_FORMAT_R32_FLOAT,
  DXGI_FORMAT_R32_UINT,
  DXGI_FORMAT_R32_SINT,
  DXGI_FORMAT_R24G8_TYPELESS,
  DXGI_FORMAT_D24_UNORM_S8_UINT,
  DXGI_FORMAT_R24_UNORM_X8_TYPELESS,
  DXGI_FORMAT_X24_TYPELESS_G8_UINT,
  DXGI_FORMAT_R8G8_TYPELESS,
  DXGI_FORMAT_R8G8_UNORM,
  DXGI_FORMAT_R8G8_UINT,
  DXGI_FORMAT_R8G8_SNORM,
  DXGI_FORMAT_R8G8_SINT,
  DXGI_FORMAT_R16_TYPELESS,
  DXGI_FORMAT_R16_FLOAT,
  DXGI_FORMAT_D16_UNORM,
  DXGI_FORMAT_R16_UNORM,
  DXGI_FORMAT_R16_UINT,
  DXGI_FORMAT_R16_SNORM,
  DXGI_FORMAT_R16_SINT,
  DXGI_FORMAT_R8_TYPELESS,
  DXGI_FORMAT_R8_UNORM,
  DXGI_FORMAT_R8_UINT,
  DXGI_FORMAT_R8_SNORM,
  DXGI_FORMAT_R8_SINT,
  DXGI_FORMAT_A8_UNORM,
  DXGI_FORMAT_R1_UNORM,
  DXGI_FORMAT_R9G9B9E5_SHAREDEXP,
  DXGI_FORMAT_R8G8_B8G8_UNORM,
  DXGI_FORMAT_G8R8_G8B8_UNORM,
  DXGI_FORMAT_BC1_TYPELESS,
  DXGI_FORMAT_BC1_UNORM,
  DXGI_FORMAT_BC1_UNORM_SRGB,
  DXGI_FORMAT_BC2_TYPELESS,
  DXGI_FORMAT_BC2_UNORM,
  DXGI_FORMAT_BC2_UNORM_SRGB,
  DXGI_FORMAT_BC3_TYPELESS,
  DXGI_FORMAT_BC3_UNORM,
  DXGI_FORMAT_BC3_UNORM_SRGB,
  DXGI_FORMAT_BC4_TYPELESS,
  DXGI_FORMAT_BC4_UNORM,
  DXGI_FORMAT_BC4_SNORM,
  DXGI_FORMAT_BC5_TYPELESS,
  DXGI_FORMAT_BC5_UNORM,
  DXGI_FORMAT_BC5_SNORM,
  DXGI_FORMAT_B5G6R5_UNORM,
  DXGI_FORMAT_B5G5R5A1_UNORM,
  DXGI_FORMAT_B8G8R8A8_UNORM,
  DXGI_FORMAT_B8G8R8X8_UNORM,
  DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM,
  DXGI_FORMAT_B8G8R8A8_TYPELESS,
  DXGI_FORMAT_B8G8R8A8_UNORM_SRGB,
  DXGI_FORMAT_B8G8R8X8_TYPELESS,
  DXGI_FORMAT_B8G8R8X8_UNORM_SRGB,
  DXGI_FORMAT_BC6H_TYPELESS,
  DXGI_FORMAT_BC6H_UF16,
  DXGI_FORMAT_BC6H_SF16,
  DXGI_FORMAT_BC7_TYPELESS,
  DXGI_FORMAT_BC7_UNORM,
  DXGI_FORMAT_BC7_UNORM_SRGB,
  DXGI_FORMAT_AYUV,
  DXGI_FORMAT_Y410,
  DXGI_FORMAT_Y416,
  DXGI_FORMAT_NV12,
  DXGI_FORMAT_P010,
  DXGI_FORMAT_P016,
  DXGI_FORMAT_420_OPAQUE,
  DXGI_FORMAT_YUY2,
  DXGI_FORMAT_Y210,
  DXGI_FORMAT_Y216,
  DXGI_FORMAT_NV11,
  DXGI_FORMAT_AI44,
  DXGI_FORMAT_IA44,
  DXGI_FORMAT_P8,
  DXGI_FORMAT_A8P8,
  DXGI_FORMAT_B4G4R4A4_UNORM,
  DXGI_FORMAT_P208,
  DXGI_FORMAT_V208,
  DXGI_FORMAT_V408,
  DXGI_FORMAT_FORCE_UINT
};

struct DDS_HEADER_DXT10 {
  DXGI_FORMAT              dxgiFormat{};
  D3D10_RESOURCE_DIMENSION resourceDimension{D3D10_RESOURCE_DIMENSION_TEXTURE2D};
  UINT                     miscFlag{};
  UINT                     arraySize{};
  UINT                     miscFlags2{};
};

#ifdef _WIN32
#	pragma pack(pop)
#else
#	pragma pack()
#endif

#endif // DDS_HEADER_H
